[package]
name = "visualizer"
version = "0.1.0"
authors = ["Steven Cohen <peragwin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
specs = "0.16.1"
audio = { path = "../audio" }
clap = "3.0.0-beta.2"
# amethyst = "0.15.3"
# serde = { version="1.0.117", features=["derive"] }
